// images
import avatar1 from '../../../../assets/images/users/avatar-6.jpg';
import avatar2 from '../../../../assets/images/users/avatar-7.jpg';
import avatar3 from '../../../../assets/images/users/avatar-8.jpg';

const tasks = [
    {
        id: 1,
        title: 'Ubold v3.0 - Redesign',
        status: 'Pending',
        priority: 'High',
        userAvatar: avatar1,
        project: 'Hyper',
        totalComments: 28,
        totalSubTasks: 10,
        user: 'CoderThemes',
        dueDate: 'Jul 18, 2019',
    },
    {
        id: 2,
        title: 'Minton v3.0 - Redesign',
        status: 'Inprogress',
        priority: 'Low',
        userAvatar: avatar2,
        project: 'Hyper',
        totalComments: 21,
        totalSubTasks: 7,
        user: 'CoderThemes2',
        dueDate: 'Jul 20, 2019',
    },
    {
        id: 3,
        title: 'Hyper v2.1 - Angular and Django',
        status: 'Review',
        priority: 'Low',
        userAvatar: avatar1,
        project: 'Hyper2',
        totalComments: 24,
        totalSubTasks: 2,
        user: 'CoderThemes',
        dueDate: 'Jul 21, 2019',
    },
    {
        id: 4,
        title: 'Hyper v2.1 - React, Webpack',
        status: 'Done',
        priority: 'High',
        userAvatar: avatar2,
        project: 'Hyper2',
        totalComments: 21,
        totalSubTasks: 5,
        user: 'CoderThemes2',
        dueDate: 'Jul 22, 2019',
    },
    {
        id: 5,
        title: 'Hyper 2.2 - Vue.Js and Laravel',
        status: 'Pending',
        priority: 'Low',
        userAvatar: avatar3,
        project: 'Hyper',
        totalComments: 2,
        totalSubTasks: 0,
        user: 'CoderThemes3',
        dueDate: 'Jul 18, 2019',
    },
    {
        id: 6,
        title: 'Hyper 2.3 - Rails, NodeJs, Mean',
        status: 'Pending',
        priority: 'Medium',
        userAvatar: avatar2,
        project: 'Hyper2',
        totalComments: 24,
        totalSubTasks: 8,
        user: 'CoderThemes',
        dueDate: 'Jul 21, 2019',
    },
    {
        id: 7,
        title: 'Hyper - Landing page and UI Kit',
        status: 'Review',
        priority: 'Medium',
        userAvatar: avatar3,
        project: 'Hyper',
        totalComments: 11,
        totalSubTasks: 6,
        user: 'CoderThemes',
        dueDate: 'Jul 10, 2019',
    },
    {
        id: 8,
        title: 'Hyper 3.0 - Scoping',
        status: 'Inprogress',
        priority: 'High',
        userAvatar: avatar2,
        project: 'Hyper2',
        totalComments: 10,
        totalSubTasks: 4,
        user: 'CoderThemes2',
        dueDate: 'Jul 24, 2019',
    },
];

export { tasks };
