export enum TeamActionTypes {
  API_RESPONSE_SUCCESS = '@@team/API_RESPONSE_SUCCESS',
  API_RESPONSE_ERROR = '@@team/API_RESPONSE_ERROR',

  CREATE_TEAM = '@@team/CREATE_TEAM',
  READ_ALL_TEAM = '@@team/READ_ALL_TEAM',
  READ_TEAM = '@@team/READ_TEAM',
  UPDATE_TEAM = '@@team/UPDATE_TEAM',
  LEAVE_TEAM = '@@team/LEAVE_TEAM',
  CHANGE_TEAM = '@@team/CHANGE_TEAM',
  CREATE_MEETING = '@@team/CREATE_MEETING',
  DELETE_MEETING = '@@team/DELETE_MEETING',

  RESET = '@@team/RESET',
}
