import { DailyStandup, Whiteboard } from './types';
import profileImg from './Komputer_P.png'

const dailyStandups: DailyStandup[] = [
    {
        id: 1,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: true,
    },
    {
        id: 2,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
    {
        id: 3,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
    {
        id: 4,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
    {
        id: 5,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
    {
        id: 6,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
    {
        id: 7,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
    {
        id: 8,
        author: "Komputer P",
        profileImageUrl: profileImg,
        lastModifiedDate: '2022-08-03T01:13:14',
        recordFileUrl: 'https://wbj-media.s3.ap-northeast-2.amazonaws.com/records/record_4_23.webm',
        seen: false,
    },
]

const whiteboards: Whiteboard[] = [
    {
        id: 1,
        title: 'whiteboard 1',
        description: 'This whiteboard is for testing',
        author: 'Dongun Yi',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 2,
        title: 'whiteboard 2',
        description: 'This whiteboard is for testing',
        author: 'Jin Lee',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 3,
        title: 'whiteboard 3',
        description: 'This whiteboard is for testing',
        author: 'Jihwan Park',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 4,
        title: 'whiteboard 4',
        description: 'This whiteboard is for testing',
        author: 'Komputer P',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 5,
        title: 'whiteboard 5',
        description: 'This whiteboard is for testing',
        author: 'Dongun Yi',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 6,
        title: 'whiteboard 1',
        description: 'This whiteboard is for testing',
        author: 'Dongun Yi',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
]

export { dailyStandups, whiteboards }