import { Whiteboard } from './types';

const whiteboards: Whiteboard[] = [
    {
        id: 1,
        title: 'whiteboard 1',
        description: 'This whiteboard is for testing',
        author: 'Dongun Yi',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 2,
        title: 'whiteboard 2',
        description: 'This whiteboard is for testing',
        author: 'Jin Lee',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 3,
        title: 'whiteboard 3',
        description: 'This whiteboard is for testing',
        author: 'Jihwan Park',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 4,
        title: 'whiteboard 4',
        description: 'This whiteboard is for testing',
        author: 'Komputer P',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 5,
        title: 'whiteboard 5',
        description: 'This whiteboard is for testing',
        author: 'Dongun Yi',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
    {
        id: 6,
        title: 'whiteboard 1',
        description: 'This whiteboard is for testing',
        author: 'Dongun Yi',
        scope: 'scope',
        createdDate: 'July 22, 2022',
        lastModifiedDate: 'July 22, 2022',
        whiteboardFileUrl: '',
    },
]

export { whiteboards }